### ISSUE TITLE
[1.19.2] Spruce plank wall recipe conflict

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Undeco#4]
Mod version: 1.19-1.3.0
Forge: 43.1.2

The crafting recipe for the spruce trap door and the undeco spruce wall (planks) conflicts.

Discovered on the TF testing server

(I will also note that while ornamental has a link to its issue tracker, undeco does not which is why I've reported to the wrong repo a couple times)

**Comment by Andromander** [comment]
I said "Fix #4"
